home/urls.py
from django.urls import path
from .views import index, about, contacts


urlpatterns = [
    path('', index),
    path('index', index),
    path('about', about),
    path('contacts', contacts)
]

knit_webnotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('calculator/', include('calculator.urls')),
    path('patterns/', include('patterns.urls')),
    path('samples/', include('samples.urls')),
    path('tools/', include('tools.urls')),
    path('webnotes/', include('webnotes.urls')),
    path('yarns/', include('yarns.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webnotes/urls.py
from django.urls import re_path, path
from .views import index, create, details, edit, delete, public


urlpatterns = [
    re_path(r'^(?P<user_id>[0-9]+)$', index),
    re_path(r'^index/(?P<user_id>[0-9]+)$', index),
    path('create', create),
    re_path(r'^details/(?P<webnote_id>[0-9]+)$', details),
    re_path(r'^edit/(?P<webnote_id>[0-9]+)$', edit),
    re_path(r'^delete/(?P<webnote_id>[0-9]+)$', delete),
    path('public', public),
]

webnotes/models.py
from django.db import models
from django.contrib.auth.models import User


class Status(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self):
        return self.name


class Craft(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self):
        return self.name


class Access (models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self):
        return self.name


class Tool(models.Model):
    name = models.CharField(max_length=100, null=False)
    size = models.FloatField(null=False)
    producer = models.CharField(max_length=100, null=True, blank=True)
    type = models.CharField(max_length=100, null=True, blank=True)
    material = models.CharField(max_length=100, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}: {self.size}мм - {self.producer}'


class Pattern(models.Model):
    name = models.CharField(max_length=100, unique=True, null=False)
    image = models.FileField(null=True, upload_to='upload/patterns/image', blank=True)
    scheme = models.FileField(null=True, upload_to='upload/patterns/scheme', blank=True)
    description = models.TextField(max_length=1024)
    source = models.URLField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Yarn(models.Model):
    name = models.CharField(max_length=100, null=False)
    color_lot = models.CharField(max_length=100, null=False)
    weight = models.PositiveIntegerField(null=True, blank=True)
    length = models.PositiveIntegerField(null=True, blank=True)
    label = models.FileField(null=True, upload_to='upload/yarns', blank=True)
    source = models.URLField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}:{self.color_lot}/{self.weight}гр-{self.length}м'


class Webnote(models.Model):
    project_name = models.CharField(max_length=100, null=False)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    create_date = models.DateTimeField(null=False, auto_now_add=True)
    for_who = models.CharField(max_length=100, null=False)
    craft = models.ForeignKey(Craft, verbose_name='Вид рукоделия', on_delete=models.CASCADE, default=0)
    image = models.FileField(null=True, upload_to='upload/webnotes', blank=True)
    note = models.TextField(max_length=512, null=True, blank=True)
    access = models.ForeignKey(Access, verbose_name='Доступ другим пользователям', on_delete=models.CASCADE, default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, verbose_name='Статус', on_delete=models.CASCADE, default=0)
    tool = models.ManyToManyField(Tool, verbose_name='Инструменты')
    pattern = models.ManyToManyField(Pattern, verbose_name='Узор')
    yarn = models.ManyToManyField(Yarn, verbose_name='Пряжа')

    def __str__(self):
        return f'{self.project_name}: {self.craft}/{self.status}/{self.access}'

webnotes/forms.py
from django import forms
from .models import Webnote


class WebnoteForm(forms.ModelForm):
    project_name = forms.CharField(label='Название проекта')
    start_date = forms.DateField(label='Дата начала', widget=forms.SelectDateWidget)
    end_date = forms.DateField(label='Дата окончания', widget=forms.SelectDateWidget)
    for_who = forms.CharField(label='Для кого')
    image = forms.FileField(label='Фото изделия')
    note = forms.CharField(label='Описание проекта', widget=forms.Textarea)

    class Meta:
        model = Webnote
        fields = ('project_name', 'start_date', 'end_date', 'for_who', 'craft', 'image',
                  'note', 'access', 'user', 'status')
        # , 'tool', 'pattern', 'yarn'


class WebnoteForm2(forms.ModelForm):
    project_name = forms.CharField(label='Название проекта')
    start_date = forms.DateField(label='Дата начала', widget=forms.SelectDateWidget)
    end_date = forms.DateField(label='Дата окончания', widget=forms.SelectDateWidget)
    for_who = forms.CharField(label='Для кого')
    note = forms.CharField(label='Описание проекта', widget=forms.Textarea)

    class Meta:
        model = Webnote
        fields = ('project_name', 'start_date', 'end_date', 'for_who', 'craft',
                  'note', 'access', 'status')
        # , 'tool', 'pattern', 'yarn'

webnotes/views.py
from django.shortcuts import render, redirect
from .models import Webnote, Pattern, Tool, Yarn
from .forms import WebnoteForm, WebnoteForm2
from django.contrib.auth import logout
from django.core.paginator import Paginator


def index(request, user_id):
    data = dict()
    data['title'] = 'Мой Веб-блокнот'
    if request.user.is_authenticated:
        all_webnotes = Webnote.objects.filter(user=user_id)
        #
        # pat = []
        # for w in all_webnotes:
        #     pattern = Webnote.objects.get(id=w.id).pattern.all()
        #     # tool = Webnote.objects.get(id=w.id).tool.all()
        #     # yarn = Webnote.objects.get(id=w.id).yarn.all()
        #     # print(w, pattern)
        #     # pat.append(w)
        #     pat.append(pattern)
        #     # pat.append(tool)
        #     # pat.append(yarn)
        # # data['pattern'] = pat
        # print(pat)
        data['webnotes'] = all_webnotes
        # data['pattern'] = pat
    else:
        logout(request)
        return redirect('/accounts/sign_up')
    paginator = Paginator(all_webnotes, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    data['page_obj'] = page_obj

    return render(request, 'webnotes/index.html', context=data)


def create(request):
    data = dict()
    data['title'] = 'Создание записи в Веб-блокноте'
    if request.method == 'GET':
        # Блокировка доступа через адресную строку
        # superadmim1 : 777sssL
        if request.user.is_authenticated:
            data['form_webnote'] = WebnoteForm()
            data['form_pattern'] = Pattern.objects.filter(user=request.user.id)
            data['form_tool'] = Tool.objects.filter(user=request.user.id)
            data['form_yarn'] = Yarn.objects.filter(user=request.user.id)
            # print(data['form_pattern'], data['form_tool'], data['form_yarn'])
            return render(request, 'webnotes/create.html', context=data)
        else:
            logout(request)
            return redirect('/accounts/sign_up')
    elif request.method == 'POST':
        filled_form = WebnoteForm(request.POST, request.FILES)
        print(filled_form.data)
        filled_form.save()
        # перенаправляем на страничку webnotes
        return redirect(f'/webnotes/{request.user.id}')


def details(request, webnote_id):
    data = dict()
    data['title'] = 'Просмотр записи о проекте'
    if request.method == 'GET':
        data['webnote'] = Webnote.objects.get(id=webnote_id)
        return render(request, 'webnotes/details.html', context=data)


def edit(request, webnote_id):
    data = dict()
    data['title'] = 'Редактирование записи в Веб-блокноте'
    webnote = Webnote.objects.get(id=webnote_id)
    if request.method == 'GET':
        if request.user.is_authenticated:
            data['form'] = WebnoteForm2(instance=webnote)
            data['webnote'] = webnote
            data['form_pattern'] = Pattern.objects.filter(user=request.user.id)
            data['form_tool'] = Tool.objects.filter(user=request.user.id)
            data['form_yarn'] = Yarn.objects.filter(user=request.user.id)
            return render(request, 'webnotes/edit.html', context=data)
        else:
            logout(request)
            return redirect('/accounts/sign_up')
    elif request.method == 'POST':
        form2 = WebnoteForm2(request.POST)
        if form2.is_valid():
            webnote.project_name = form2.cleaned_data['project_name']
            webnote.start_date = form2.cleaned_data['start_date']
            webnote.end_date = form2.cleaned_data['end_date']
            webnote.for_who = form2.cleaned_data['for_who']
            webnote.craft = form2.cleaned_data['craft']
            webnote.note = form2.cleaned_data['note']
            webnote.access = form2.cleaned_data['access']
            webnote.status = form2.cleaned_data['status']
            webnote.save()
        return redirect(f'/webnotes/{request.user.id}')


def delete(request, webnote_id):
    data = dict()
    data['title'] = 'Удаление записи о проекте из Веб-блокнота'
    webnote = Webnote.objects.get(id=webnote_id)
    if request.method == 'GET':
        # Блокировка доступа через адресную строку
        if request.user.is_authenticated:
            data['webnote'] = webnote
            return render(request, 'webnotes/delete.html', context=data)
        else:
            logout(request)
            return redirect('/accounts/sign_up')
    elif request.method == 'POST':
        webnote.delete()
        return redirect(f'/webnotes/{request.user.id}')


def public(request):
    data = dict()
    data['title'] = 'Коллекция Веб-записей'
    public_webnotes = Webnote.objects.filter(access=2)
    data['webnotes'] = public_webnotes
    paginator = Paginator(public_webnotes, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    data['page_obj'] = page_obj
    return render(request, 'webnotes/public.html', context=data)

templates/webnotes/create.html
{% extends 'layout/base.html' %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
<div id="content" class="container">
    <h2 class="title">{{ title }}</h2>
</div>
<div class="container">
    <div class="card" id="card_info">
        <div class="card-header" id="heading_info">
            Общая информация
        </div>
        <div class="card card-body">
            <form method="post" action="/webnotes/create" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form_webnote %}
                    {% if field.label == 'User' %}
                        <div class="form-group">
                            <input type="hidden" name="user" value="{{ user.id }}">
                        </div>
                    {% else %}
                        <div class="form-group">
                            {{ field.label }}
                            <div>{{ field }}</div>
                        </div>
                    {% endif %}
                {% endfor %}
                <div class="form-group">
                    <label for="id_pattern">Узор</label><br>
                        <select name="pattern" id="id_pattern" size="3">
                            {% for pattern in form_pattern %}
                                <option value="{{ pattern.id }}">{{ pattern }}</option>
                            {% endfor %}
                        </select>
                </div>
                <div class="form-group">
                    <label for="id_tool">Инструменты</label><br>
                        <select name="tool" id="id_tool" size="3">
                            {% for tool in form_tool %}
                                <option value="{{ tool.id }}">{{ tool }}</option>
                            {% endfor %}
                        </select>
                </div>
                <div class="form-group">
                    <label for="id_yarn">Пряжа</label><br>
                        <select name="yarn" id="id_yarn" size="3">
                            {% for yarn in form_yarn %}
                                <option value="{{ yarn.id }}">{{ yarn }}</option>
                            {% endfor %}
                        </select>
                </div>
                <p style="margin-top: 20px">
                    <input id="save" type="submit" value="Сохранить" class="btn btn-success">
                    <input id="cancel" type="reset" value="Очистить" class="btn btn-secondary">
                </p>
            </form>
        </div>
        <h5 class="card-title">
            <a class="btn btn-link" href="/webnotes/{{ user.id }}" role="button">Вернуться к записям в Веб-блокноте</a>
        </h5>
    </div>
</div>
<style>
    .form-group input{
        width: 50%;
        height: 30px;
    }
    .form-group textarea {
        width: 50%;
    }
</style>
{% endblock content %}

templates/webnotes/delete.html
{% extends 'layout/base.html' %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
    <div class="container">
        <h2 class="title">{{ title }}</h2>
        <div class="card" id="card_info">
            <div class="card-header" id="heading_info">
                <h4>Подтвердите удаление записи:</h4>
            </div>
            <div class="card card-body">
                <h5>{{ webnote.project_name }} / {{ webnote.status}} / {{webnote.create_date}}</h5>

                <form action="/webnotes/delete/{{ webnote.id }}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Удалить" class="btn btn-secondary" style="width: 200px">
                </form>
            </div>
            <h5 class="card-title">
                <a class="btn btn-link" href="/webnotes/{{ user.id }}" role="button">Вернуться к записям в Веб-блокноте</a>
            </h5>
        </div>
    </div>
{% endblock content %}

templates/webnotes/details.html
{% extends 'layout/base.html' %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
    <div class="container">
        <h2 class="title">{{ title }}</h2>
        <div class="card">
            <div class="card-header">
                {{ webnote.craft }}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{webnote.project_name}}</h5>
                <img src="/media/{{ webnote.image }}" width="30%" align="left" style="margin-right: 50px">
                <p class="card-text"><b>Дата начала:</b> {{ webnote.start_date|date:'d-m-Y' }} - <b>Дата окончания:</b> {{ webnote.end_date|date:'d-m-Y' }}</p>
                <p class="card-text"><b>Кому:</b> {{ webnote.for_who }}</p>
                <p class="card-text"><b>Описание:</b> {{ webnote.note }}</p>
                <p class="card-text"><b>Статус:</b> {{ webnote.status }}
                    <span class="badge badge-info">{{ webnote.access }}</span>
                </p>
                <p class="card-text">
                    <small class="text-muted">Запись добавлена: {{ webnote.create_date|date:'d-m-Y h:m:s' }}</small>
                </p>
                {% if user.is_authenticated %}
                    <a class="btn btn-link" href="/webnotes/{{ user.id }}" role="button">Вернуться к записям в Веб-блокноте</a>
                {% else %}
                    <a class="btn btn-link" href="/webnotes/public" role="button">Вернуться к записям в Веб-блокноте</a>
                {% endif %}
          </div>
        </div>

    </div>
{% endblock content %}

templates/webnotes/edit.html
{% extends 'layout/base.html' %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
    <div class="container">
        <h1 class="title">{{ title }}</h1>
    </div>
    <div class="container">
        <div class="card" id="card_info">
            <div class="card-header" id="heading_info">
                Общая информация
            </div>
            <div class="card card-body">
                <form action="/webnotes/edit/{{ webnote.id }}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label }}
                            <div>{{ field }}</div>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                    <label for="id_pattern">Узор</label><br>
                        <select name="pattern" id="id_pattern" size="3">
                            {% for pattern in form_pattern %}
                                <option value="{{ pattern.id }}">{{ pattern }}</option>
                            {% endfor %}
                        </select>
                </div>
                    <div class="form-group">
                    <label for="id_tool">Инструменты</label><br>
                        <select name="tool" id="id_tool" size="3">
                            {% for tool in form_tool %}
                                <option value="{{ tool.id }}">{{ tool }}</option>
                            {% endfor %}
                        </select>
                </div>
                    <div class="form-group">
                    <label for="id_yarn">Пряжа</label><br>
                        <select name="yarn" id="id_yarn" size="3">
                            {% for yarn in form_yarn %}
                                <option value="{{ yarn.id }}">{{ yarn }}</option>
                            {% endfor %}
                        </select>
                </div>
                    <p style="margin-top: 20px">
                        <input id="save" type="submit" value="Сохранить" class="btn btn-success">
                        <input id="cancel" type="reset" value="Очистить" class="btn btn-secondary">
                    </p>
                </form>
            </div>
            <h5 class="card-title">
                <a class="btn btn-link" href="/webnotes/{{ user.id }}" role="button">Вернуться к записям в Веб-блокноте</a>
            </h5>
        </div>
    </div>
    <style>
    .form-group input{
        width: 50%;
        height: 30px;
    }
    .form-group textarea {
        width: 50%;
    }
</style>
{% endblock content %}

templates/webnotes/index.html
{% extends 'layout/base.html' %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
<div class="container" style="margin: 0px 50px">
    <h1 class="title" style="margin: 50px;">{{ title }}</h1>
    <div class="row" style="margin: 10px 0px">
        <div class="col-md-3" style="border-right: solid 1px #b9d3c6">
            {% if user.is_authenticated %}
                <a href="/webnotes/create" id="btn_add_notes" class="btn btn-info" role="button">Добавить запись</a>
            {% endif %}

            <ul class="list-group" style="width:80%">
                <li class="list-group-item">
                    <a class="link" href="/webnotes/{{ user.id }}">Мой Веб-блокнот</a>
                    <hr>
                    <ul class="list-group" style="list-style-type: none; padding: 0px 10px ;" >
                        <li><a class="link" href="/webnotes/{{ user.id }}">Все проекти</a></li>
                        <li><a class="link" href="#">Публичные</a></li>
                        <li><a class="link" href="#">Приватные</a></li>
                        <li><a class="link" href="#">Завершенные</a></li>
                        <li><a class="link" href="#">В процессе</a></li>
                    </ul>
                </li>
                <li class="list-group-item">
                        <a class="link" href="/patterns/{{ user.id }}"> Мои Узоры</a>
                </li>
                <li class="list-group-item">
                    <a class="link" href="/tools/{{ user.id }}">Инструменты</a>
                </li>
                <li class="list-group-item">
                    <a class="link" href="/yarns/{{ user.id }}">Пряжа</a>
                </li>

            </ul>
        </div>
        <div class="col-md-8">
            {% for webnote in page_obj %}
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img src="/media/{{ webnote.image }}" class="card-img" alt="Фото изделия">
                        </div>
                        <div class="col-md-4">
                            <div class="card-body">
                                <h5 class="card-title">{{ webnote.project_name }}
                                    <span class="badge badge-pill badge-success">{{ webnote.access }}</span>
                                </h5>
                                <p class="card-text">
                                    Кому: {{ webnote.for_who }}<br>Статус: {{ webnote.status }}
                                </p>
                                <p class="card-text">{{ webnote.note }}<br>
                                    <small class="text-muted">{{ webnote.craft }}</small>
                                </p>
                                <!--<p class="card-text">Узор: {{ pattern.pattern.name }}</p>-->
                                <!--<p class="card-text">Пряжа: {{ yarn.name }}</p>-->
                                <!--<p class="card-text">Инструменты: {{ tool.name }}</p>-->
                            </div>
                            <p>
                                <a class="btn-outline-success" href="/webnotes/details/{{ webnote.id }}" role="button">Просмотреть</a>
                                {% if user.is_authenticated %}
                                    <a class="btn-outline-info" href="/webnotes/edit/{{ webnote.id }}" role="button">Изменить</a>
                                    <a class="btn-outline-secondary" href="/webnotes/delete/{{ webnote.id }}" role="button">Удалить</a>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="pagination" style="margin-top: 20px">
                <nav aria-label="Page navigation example">
            <ul class="pagination">
                <!--Переход назад на предыдущую страницу-->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page=1">1</a>
                </li>
                {% endif %}
                <!--Номер текущей страницы-->
                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                </li>
                <!--Переход вперед на следующую страницу-->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
            </div>
        </div>
    </div>
</div>
<style>
    main{
        height: 100%;
        background-image: url("../../static/img/style/St4_Big_12_1.jpg");
        background-size: cover;
    }
    #btn_add_notes {
        margin-bottom: 20px;
    }
</style>
{% endblock content %}

templates/webnotes/public.html
{% extends 'layout/base.html' %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
<div class="container" style="margin: 0px 50px">
    <h1 class="title" style="margin: 50px;">{{ title }}</h1>
    <div class="row" style="margin: 10px 0px">
        {% for webnote in page_obj %}
            <div class="col-md-4">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row no-gutters">
                        <h5 class="card-title">{{ webnote.user }}</h5>
                        <img src="/media/{{ webnote.image }}" class="card-img" alt="Фото изделия">
                        <div class="card-body">
                            <h5 class="card-title">{{ webnote.project_name }}</h5>
                            <p class="card-text">Статус: {{ webnote.status }}</p>
                            <p class="card-text">{{ webnote.note }}<br>
                                <small class="text-muted">{{ webnote.craft }}</small>
                            </p>
                            <!--<p class="card-text">Узор: {{ webnote.pattern }}</p>-->
                            <!--<p class="card-text">Пряжа: {{ webnote.yarn }}</p>-->
                            <!--<p class="card-text">Инструменты: {{ webnote.tool }}</p>-->
                        </div>
                        <p>
                            <a class="btn-outline-success" href="/webnotes/details/{{ webnote.id }}" role="button">Посмотреть</a>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    <div class="pagination" style="margin-top: 20px">
                <nav aria-label="Page navigation example">
            <ul class="pagination">
                <!--Переход назад на предыдущую страницу-->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page=1">1</a>
                </li>
                {% endif %}
                <!--Номер текущей страницы-->
                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                </li>
                <!--Переход вперед на следующую страницу-->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
            </div>
</div>
<style>
    main{
        height: 100%;
        background-image: url("../../static/img/style/St4_Big_12_1.jpg");
        background-size: cover;
    }
</style>
{% endblock content %}